language: node_js
node_js:
- 0.10
- 0.11
- 0.12
before_install:
- npm i -g npm@2.8.1
- npm i -g jshint
- jshint . 
- npm i -g jasmine@2.2.0
- npm i -g istanbul
- npm install git://github.com/JacobeanRnD/SCXMLD-postgres-database-provider#5d2efc2b9229113f3252dbf559457901946be6bf
- export WEBSITE_URL='http://scxmldev.io'
- export POSTGRES_URL='postgres://postgres@localhost:5432/scxmld'
before_script:
- psql -c 'create database scxmld;' -U postgres
addons:
  postgresql: "9.3"